export interface ControlPlaneStatus {
  readonly sessions: { readonly total: number; readonly active: number; readonly closed: number };
  readonly approvals: { readonly total: number; readonly pending: number; readonly approved: number; readonly rejected: number };
  readonly telemetry: { readonly calls: number; readonly successful: number; readonly total_tokens: number };
}

export interface SessionRecord { readonly session_id: string; readonly agent_command: string; readonly cwd: string; readonly name: string | null; readonly status: "active" | "closed"; readonly created_at: string; readonly updated_at: string; readonly owner_expires_at: string | null; readonly queue: readonly { readonly prompt_id: string; readonly queued_at: string }[]; readonly close_reason?: string }
export interface ApprovalRecord { readonly schema_version: "v1"; readonly approval_id: string; readonly session_id: string; readonly vendor: string; readonly model: string | null; readonly skill_ids: readonly string[]; readonly prompt_preview: string; readonly prompt_file: string | null; readonly estimated_tokens: number; readonly status: "pending" | "approved" | "rejected"; readonly created_at: string; readonly decided_at: string | null; readonly rejection_reason: string | null }
export interface ProviderQuotaWindow { readonly limit: number | null; readonly used: number | null; readonly remaining: number | null; readonly resets_at: string | null }
export interface ProviderModel { readonly model_id: string; readonly available: boolean; readonly health: string; readonly source: string; readonly fetched_at?: string | null; readonly updated_at?: string | null }
export interface ProviderQuota { readonly provider: string; readonly source: string; readonly fetched_at: string; readonly observed_at: string; readonly five_hour: ProviderQuotaWindow; readonly weekly: ProviderQuotaWindow; readonly api_spend: number | null; readonly currency: string | null; readonly models: readonly ProviderModel[]; readonly health: string; readonly error_code: string | null; readonly freshness: "fresh" | "stale" | "unavailable"; readonly next_poll_at: string | null }
export interface ProviderModels { readonly freshness: string; readonly fetched_at: string | null; readonly next_poll_at: string | null; readonly models: readonly { readonly model_id: string; readonly providers: readonly string[]; readonly available: boolean; readonly health: readonly string[]; readonly fetched_at?: string | null; readonly updated_at?: string | null }[] }
export interface ProviderHealth { readonly providers: readonly { readonly provider: string; readonly health: string; readonly freshness: string; readonly fetched_at: string; readonly next_poll_at: string | null; readonly error_code: string | null }[] }
export interface WorkerRecord { readonly worker_run_id: string; readonly vendor: string; readonly model: string | null; readonly session_id: string; readonly status: "running" | "completed" | "blocked" | "error"; readonly started_at: string; readonly finished_at?: string | null; readonly output?: string | null; readonly error_reason?: string | null }
export interface ObservabilitySummary { readonly events: number; readonly tokens: number; readonly retries: number; readonly refusals: number; readonly openrouter_cost_usd: number; readonly waste_signals: readonly { readonly kind: "duplicate_dispatch" | "repeated_input_token_count"; readonly evidence_key: string; readonly occurrences: number }[] }
export interface ObservabilityEvent { readonly at: string; readonly source: "dispatch" | "cli_call" | "token_gateway" | "openrouter_spend" | "provider_quota" | "audit"; readonly event: string; readonly session_id: string | null; readonly handoff_id: string | null; readonly worker_run_id: string | null; readonly provider: string | null; readonly model: string | null; readonly tokens: number; readonly retries: number; readonly refused: boolean; readonly cost_usd: number; readonly detail: string | null }
export interface ObservabilityTimeline { readonly summary: ObservabilitySummary; readonly timeline: readonly ObservabilityEvent[]; readonly limits: { readonly files_scanned: number; readonly max_bytes_per_file: number; readonly max_lines_per_file: number; readonly max_events: number; readonly truncated: boolean } }
export interface ProjectEntry { readonly schema_version: "v1"; readonly project_id: string; readonly name: string; readonly cwd: string; readonly enabled: boolean }
export type RunStatus = "draft" | "approved" | "queued" | "running" | "completed" | "failed" | "cancelled";
export type RunProvider = "codex_cli" | "claude_cli" | "agy_cli" | "openrouter_api";
export type RunArtifactType = "text" | "visual";
export interface RunDraftInput { readonly project_id: string; readonly prompt: string; readonly provider: RunProvider; readonly model: string | null; readonly estimated_tokens: number; readonly requested_artifacts: readonly RunArtifactType[]; readonly prompt_review_acknowledged?: boolean }
export interface RunDraft extends RunDraftInput { readonly run_id: string; readonly revision: number; readonly created_at: string }
export interface RunReservation { readonly reservationId: string; readonly provider: string; readonly model: string | null; readonly sessionId: string | null; readonly inputTokens: number; readonly outputTokens: number; readonly handoffId?: string; readonly reservedAt: string; readonly totalTokens: number }
export interface RunProviderResult { readonly refused: boolean; readonly reason: string | null; readonly worker_run_id: string | null; readonly raw_output: string; readonly exitCode: number | null; readonly errorReason: string | null; readonly lockStatus: "acquired_supervisor_spawn" | "already_locked" | "stale_replaced" | "failed" | null }
export interface RunRecord { readonly schema_version: "v1"; readonly current: RunDraft; readonly revisions: readonly RunDraft[]; readonly status: RunStatus; readonly approved_revision: number | null; readonly approved_by: string | null; readonly approved_at: string | null; readonly supervisor_task_id: string | null; readonly worker_run_id: string | null; readonly terminal_reason: string | null; readonly token_reservation: RunReservation | null; readonly reservation_status: "none" | "active" | "settled" | "released"; readonly provider_result: RunProviderResult | null; readonly cancellation_requested: boolean; readonly queue_compensation_requested: boolean; readonly dispatch_failure: string | null; readonly retry_input_tokens: number; readonly retry_output_tokens: number; readonly artifacts: readonly { readonly artifact_id: string; readonly type: RunArtifactType; readonly preview: string; readonly created_at: string }[]; readonly updated_at: string }
export interface AutopilotIncident { readonly incident_id: string; readonly recorded_at: string; readonly status: "open" | "acknowledged"; readonly acknowledged_at: string | null; readonly acknowledged_by: string | null; readonly severity: "low" | "medium" | "high" | "critical"; readonly stage: string; readonly summary: string; readonly correlation_ids: Readonly<Record<string, string>>; readonly impact: string; readonly retry_count: number; readonly event_refs: readonly string[] }
export interface RepairPacketInput { readonly expected: string; readonly actual: string; readonly reproduction_steps?: readonly string[]; readonly verification_commands?: readonly string[] }
export interface AutopilotRepairPacket { readonly schema_version: "v1"; readonly intent: "external_autopilot_repair"; readonly execution: "manual"; readonly incident: AutopilotIncident; readonly expected: string; readonly actual: string; readonly reproduction_steps: readonly string[]; readonly verification_commands: readonly string[] }
