export interface ControlPlaneStatus {
  readonly sessions: { readonly total: number; readonly active: number; readonly closed: number };
  readonly approvals: { readonly total: number; readonly pending: number; readonly approved: number; readonly rejected: number };
  readonly telemetry: { readonly calls: number; readonly successful: number; readonly total_tokens: number };
}

export interface SessionRecord { readonly session_id: string; readonly agent_command: string; readonly cwd: string; readonly name: string | null; readonly status: "active" | "closed"; readonly created_at: string; readonly updated_at: string; readonly owner_expires_at: string | null; readonly queue: readonly { readonly prompt_id: string; readonly queued_at: string }[]; readonly close_reason?: string }
export interface ApprovalRecord { readonly schema_version: "v1"; readonly approval_id: string; readonly session_id: string; readonly vendor: string; readonly model: string | null; readonly skill_ids: readonly string[]; readonly prompt_preview: string; readonly prompt_file: string | null; readonly estimated_tokens: number; readonly status: "pending" | "approved" | "rejected"; readonly created_at: string; readonly decided_at: string | null; readonly rejection_reason: string | null }
export interface ProviderQuotaWindow { readonly limit: number | null; readonly used: number | null; readonly remaining: number | null; readonly resets_at: string | null }
export interface ProviderModel { readonly model_id: string; readonly available: boolean; readonly health: string; readonly source: string; readonly fetched_at?: string | null; readonly updated_at?: string | null }
export interface ProviderQuota { readonly provider: string; readonly source: string; readonly fetched_at: string; readonly observed_at: string; readonly five_hour: ProviderQuotaWindow; readonly weekly: ProviderQuotaWindow; readonly api_spend: number | null; readonly currency: string | null; readonly models: readonly ProviderModel[]; readonly health: string; readonly error_code: string | null; readonly freshness: "fresh" | "stale" | "unavailable"; readonly next_poll_at: string | null }
export interface ProviderModels { readonly freshness: string; readonly fetched_at: string | null; readonly next_poll_at: string | null; readonly models: readonly { readonly model_id: string; readonly providers: readonly string[]; readonly available: boolean; readonly health: readonly string[]; readonly fetched_at?: string | null; readonly updated_at?: string | null }[] }
export interface ProviderHealth { readonly providers: readonly { readonly provider: string; readonly health: string; readonly freshness: string; readonly fetched_at: string; readonly next_poll_at: string | null; readonly error_code: string | null }[] }
export interface WorkerRecord { readonly worker_run_id: string; readonly vendor: string; readonly model: string | null; readonly session_id: string; readonly status: "running" | "completed" | "blocked" | "error"; readonly started_at: string; readonly finished_at?: string | null; readonly output?: string | null; readonly error_reason?: string | null }
export interface ObservabilitySummary { readonly events: number; readonly tokens: number; readonly retries: number; readonly refusals: number; readonly openrouter_cost_usd: number; readonly waste_signals: readonly { readonly kind: "duplicate_dispatch" | "repeated_input_token_count"; readonly evidence_key: string; readonly occurrences: number }[] }
export interface ObservabilityEvent { readonly at: string; readonly source: "dispatch" | "cli_call" | "token_gateway" | "openrouter_spend" | "provider_quota" | "audit"; readonly event: string; readonly session_id: string | null; readonly handoff_id: string | null; readonly worker_run_id: string | null; readonly provider: string | null; readonly model: string | null; readonly tokens: number; readonly retries: number; readonly refused: boolean; readonly cost_usd: number; readonly detail: string | null }
export interface ObservabilityTimeline { readonly summary: ObservabilitySummary; readonly timeline: readonly ObservabilityEvent[]; readonly limits: { readonly files_scanned: number; readonly max_bytes_per_file: number; readonly max_lines_per_file: number; readonly max_events: number; readonly truncated: boolean } }
