import { useCallback, useEffect, useState } from "react";
import type { CockpitView } from "./AppShell";
import type { CockpitEnvironment } from "./environment";
export type CockpitRouteState = { readonly environment: CockpitEnvironment; readonly projectId?: string; readonly sessionId?: string; readonly runId?: string; readonly view?: CockpitView };
const cockpitViews: readonly CockpitView[] = ["command", "run", "resources", "new-run", "rules"];
function readView(raw: string | null): CockpitView { return cockpitViews.find((candidate) => candidate === raw) ?? "command"; }
export function readRouteState(location: Pick<Location, "search"> = window.location): CockpitRouteState { const params = new URLSearchParams(location.search); return { environment: params.get("environment") === "prod" ? "prod" : "dev", projectId: params.get("project") || undefined, sessionId: params.get("session") || undefined, runId: params.get("run") || undefined, view: readView(params.get("view")) }; }
export function writeRouteState(state: CockpitRouteState, location: Pick<Location, "search" | "pathname" | "hash"> = window.location, history: Pick<History, "replaceState"> = window.history): void { const params = new URLSearchParams(location.search); params.set("environment", state.environment); if (state.projectId) params.set("project", state.projectId); else params.delete("project"); if (state.sessionId) params.set("session", state.sessionId); else params.delete("session"); if (state.runId) params.set("run", state.runId); else params.delete("run"); if (state.view && state.view !== "command") params.set("view", state.view); else params.delete("view"); const query = params.toString(); history.replaceState(null, "", `${location.pathname}${query ? `?${query}` : ""}${location.hash}`); }
export function useRouteState(): [CockpitRouteState, (next: CockpitRouteState) => void] { const [state, setState] = useState<CockpitRouteState>(() => readRouteState()); useEffect(() => { const onPopState = () => setState(readRouteState()); window.addEventListener("popstate", onPopState); return () => window.removeEventListener("popstate", onPopState); }, []); const update = useCallback((next: CockpitRouteState) => { writeRouteState(next); setState(next); }, []); return [state, update]; }
