export const PATTERN_REQUIREMENT_CODES = [
  "visible_h1",
  "dom_text_cta",
  "no_primary_content_in_canvas",
  "reduced_motion_fallback",
  "performance_budget",
  "proof_adjacency",
  "semantic_headings",
  "seo_readable_content",
  "accessible_copy",
  "responsive_typography",
  "trust_signal",
  "proof_evidence",
  "source_reference",
  "outcome_statement",
  "handoff_clarity",
  "brand_axis",
  "contrast_axis",
  "mobile_fallback",
  "asset_provenance",
  "asset_license",
  "demo_fallback",
  "navigation_recovery",
  "choice_model",
  "cta_path",
  "mobile_behavior",
  "accessible_links",
  "pointer_fallback",
  "keyboard_neutral_content",
  "section_anchors",
  "mobile_stacking",
  "effect_enhancement_only",
  "content_purpose",
  "content_readability",
  "visual_hierarchy",
  "line_length",
  "product_media_text",
  "pricing_clarity",
  "product_identity",
  "variant_availability_state",
  "purchase_action",
  "cart_management",
  "undo_path",
  "checkout_step_flow",
  "state_taxonomy",
  "error_state",
  "progress_indicator",
  "review_signal",
  "policy_information",
  "support_contact",
  "metric_definition",
  "comparison_context",
  "data_freshness",
  "data_source",
  "empty_loading_error_state",
  "filter_state",
  "date_range",
  "saved_view",
  "table_structure",
  "pagination_or_virtualization",
  "export_action",
  "chart_summary",
  "text_fallback",
  "severity_label",
  "timestamp",
  "ownership",
  "status_state",
  "dismissal_rule",
  "record_summary",
  "edit_state",
  "save_cancel_state",
  "focus_management",
  "selection_model",
  "permission_model",
  "confirmation_state",
  "audit_trail",
  "service_taxonomy",
  "search_affordance",
  "plain_language",
  "contact_fallback",
  "update_timestamp",
  "form_labeling",
  "validation_state",
  "office_contact",
  "account_state",
  "activity_summary",
  "document_metadata",
  "access_scope",
  "thread_state",
  "attachment_rule",
  "task_timeline",
  "server_enforcement"
] as const;

export type PatternRequirementCode = (typeof PATTERN_REQUIREMENT_CODES)[number];

export const HARD_BUILDABILITY_CODES = [
  "visible_h1",
  "dom_text_cta",
  "no_primary_content_in_canvas",
  "reduced_motion_fallback",
  "performance_budget",
  "proof_adjacency"
] as const satisfies readonly PatternRequirementCode[];

type RequirementAlias = readonly [phrase: string, codes: readonly PatternRequirementCode[]];

export const REQUIRES_ALIASES = [
  ["access scope", ["access_scope", "permission_model"]],
  ["accessible copy", ["accessible_copy"]],
  ["accessible text links for each demo", ["accessible_links", "demo_fallback"]],
  ["account state", ["account_state", "status_state"]],
  ["action-oriented columns", ["table_structure", "cta_path"]],
  ["active filter summary", ["filter_state"]],
  ["add-to-cart or detail link", ["purchase_action", "cta_path"]],
  ["address or area", ["office_contact"]],
  ["address step", ["checkout_step_flow"]],
  ["asset alt/provenance", ["asset_provenance", "accessible_copy"]],
  ["asset license", ["asset_license", "asset_provenance"]],
  ["attachment rule", ["attachment_rule"]],
  ["audit trail", ["audit_trail"]],
  ["auditable proof items", ["proof_adjacency", "proof_evidence", "source_reference"]],
  ["chart title", ["chart_summary", "accessible_copy"]],
  ["checkout CTA", ["dom_text_cta", "purchase_action"]],
  ["clear action", ["cta_path"]],
  ["clear choice model", ["choice_model"]],
  ["clear CTA path", ["cta_path"]],
  ["clear navigation back", ["navigation_recovery"]],
  ["clear route back to main page", ["navigation_recovery"]],
  ["color plus text", ["accessible_copy", "status_state"]],
  ["compact case evidence", ["proof_adjacency", "proof_evidence"]],
  ["comparison period", ["comparison_context"]],
  ["confirmation", ["confirmation_state"]],
  ["contact fallback", ["contact_fallback", "support_contact"]],
  ["content purpose", ["content_purpose"]],
  ["content readable without the effect", ["content_readability", "effect_enhancement_only"]],
  ["content-first DOM order", ["no_primary_content_in_canvas", "content_readability"]],
  ["content-first hero", ["visible_h1", "no_primary_content_in_canvas"]],
  ["contrast axis", ["contrast_axis"]],
  ["controlled line length", ["line_length"]],
  ["CTA", ["dom_text_cta", "cta_path"]],
  ["CTA continuation", ["dom_text_cta", "cta_path"]],
  ["CTA path", ["cta_path"]],
  ["data freshness", ["data_freshness"]],
  ["data source", ["data_source", "source_reference"]],
  ["date", ["timestamp"]],
  ["date range", ["date_range", "filter_state"]],
  ["default filters", ["filter_state"]],
  ["definitions", ["plain_language"]],
  ["demo link", ["demo_fallback", "cta_path"]],
  ["disabled reason", ["permission_model", "accessible_copy"]],
  ["dismiss or acknowledge rule", ["dismissal_rule"]],
  ["dismiss or expiry rule", ["dismissal_rule"]],
  ["document title", ["document_metadata"]],
  ["DOM text CTA", ["dom_text_cta"]],
  ["DOM-text CTA", ["dom_text_cta"]],
  ["download/open action", ["document_metadata", "cta_path"]],
  ["due date", ["task_timeline", "timestamp"]],
  ["editable fields", ["edit_state"]],
  ["effect/modifier, not standalone section", ["effect_enhancement_only"]],
  ["empty state", ["empty_loading_error_state"]],
  ["empty/loading/error states", ["empty_loading_error_state", "error_state"]],
  ["error states", ["error_state"]],
  ["error summary", ["error_state", "accessible_copy"]],
  ["export", ["export_action"]],
  ["fallback screenshot or summary", ["demo_fallback"]],
  ["fallback summary or screenshot", ["demo_fallback"]],
  ["field labels", ["form_labeling", "accessible_copy"]],
  ["file type", ["document_metadata"]],
  ["filters", ["filter_state"]],
  ["focus management", ["focus_management"]],
  ["freshness timestamp", ["data_freshness", "timestamp"]],
  ["handoff clarity", ["handoff_clarity"]],
  ["history", ["task_timeline", "activity_summary"]],
  ["keyboard-neutral content", ["keyboard_neutral_content", "accessible_copy"]],
  ["last updated date", ["update_timestamp"]],
  ["message timestamps", ["timestamp", "thread_state"]],
  ["metric definition", ["metric_definition"]],
  ["mobile behavior", ["mobile_behavior"]],
  ["mobile fallback", ["reduced_motion_fallback", "mobile_fallback"]],
  ["mobile stacking", ["mobile_stacking", "mobile_behavior"]],
  ["mobile stacking plan", ["mobile_stacking", "mobile_behavior"]],
  ["moderation or empty state", ["review_signal", "empty_loading_error_state"]],
  ["named views", ["saved_view"]],
  ["next action", ["cta_path"]],
  ["next actions", ["cta_path"]],
  ["no content dependency", ["content_readability"]],
  ["no decoration-only reveal", ["content_purpose", "effect_enhancement_only"]],
  ["non-motion fallback", ["reduced_motion_fallback"]],
  ["office name", ["office_contact", "ownership"]],
  ["opening hours", ["office_contact", "timestamp"]],
  ["outcome statement", ["outcome_statement"]],
  ["outcomes", ["outcome_statement"]],
  ["owner", ["ownership"]],
  ["owner office", ["ownership", "office_contact"]],
  ["owner or next action", ["ownership", "cta_path"]],
  ["owner or shared scope", ["ownership", "saved_view"]],
  ["pagination", ["pagination_or_virtualization"]],
  ["pagination or virtualization", ["pagination_or_virtualization"]],
  ["payment security note", ["policy_information", "trust_signal"]],
  ["payment step", ["checkout_step_flow"]],
  ["performance budget", ["performance_budget"]],
  ["permission checks", ["permission_model"]],
  ["permission-aware content", ["permission_model"]],
  ["phone or email", ["office_contact", "support_contact"]],
  ["plain labels", ["plain_language", "accessible_copy"]],
  ["pointer fallback", ["pointer_fallback", "mobile_fallback"]],
  ["preview count", ["selection_model"]],
  ["primary content and SEO text outside demo canvas", ["no_primary_content_in_canvas", "seo_readable_content"]],
  ["primary personality axis", ["brand_axis"]],
  ["product image alt text", ["product_media_text", "accessible_copy"]],
  ["product title", ["product_identity"]],
  ["product-proof axis", ["proof_adjacency", "proof_evidence"]],
  ["progress indicator", ["progress_indicator"]],
  ["proof adjacency", ["proof_adjacency"]],
  ["proof item", ["proof_adjacency", "proof_evidence"]],
  ["proof source", ["proof_adjacency", "source_reference"]],
  ["proof text", ["proof_adjacency", "proof_evidence"]],
  ["quantity controls", ["cart_management"]],
  ["rating summary", ["review_signal"]],
  ["reading order", ["semantic_headings", "content_readability"]],
  ["recent activity", ["activity_summary"]],
  ["record summary", ["record_summary"]],
  ["reduced-motion fallback", ["reduced_motion_fallback"]],
  ["remove or undo", ["cart_management", "undo_path"]],
  ["reply states", ["thread_state", "status_state"]],
  ["required client action", ["task_timeline", "cta_path"]],
  ["reset", ["filter_state"]],
  ["reset action", ["filter_state"]],
  ["responsive typography", ["responsive_typography"]],
  ["result count", ["filter_state"]],
  ["returns policy", ["policy_information"]],
  ["review count", ["review_signal"]],
  ["review or trust cues", ["review_signal", "trust_signal", "proof_adjacency"]],
  ["review step", ["checkout_step_flow"]],
  ["role model", ["permission_model"]],
  ["row detail", ["table_structure", "record_summary"]],
  ["row detail route", ["table_structure", "record_summary", "cta_path"]],
  ["save or recovery rule", ["save_cancel_state", "validation_state"]],
  ["save/cancel states", ["save_cancel_state"]],
  ["saved view option", ["saved_view"]],
  ["search", ["search_affordance"]],
  ["section anchors", ["section_anchors"]],
  ["selection model", ["selection_model"]],
  ["semantic headings", ["semantic_headings"]],
  ["SEO-readable content", ["no_primary_content_in_canvas", "seo_readable_content"]],
  ["SEO-readable labels", ["seo_readable_content", "accessible_copy"]],
  ["server-side enforcement", ["server_enforcement", "permission_model"]],
  ["service categories", ["service_taxonomy"]],
  ["service owner", ["ownership"]],
  ["severity", ["severity_label"]],
  ["shipping note", ["policy_information"]],
  ["shipping rule", ["policy_information"]],
  ["shipping step", ["checkout_step_flow"]],
  ["short headings", ["semantic_headings", "plain_language"]],
  ["short service description", ["plain_language", "service_taxonomy"]],
  ["sortable columns", ["table_structure"]],
  ["source", ["source_reference", "data_source"]],
  ["source identifiers", ["source_reference", "data_source"]],
  ["source or case reference", ["proof_adjacency", "source_reference"]],
  ["source/case references", ["proof_adjacency", "source_reference"]],
  ["specific headline", ["visible_h1", "semantic_headings"]],
  ["stable purchase panel", ["purchase_action"]],
  ["state labels", ["state_taxonomy", "status_state"]],
  ["state taxonomy", ["state_taxonomy"]],
  ["static fallback", ["reduced_motion_fallback", "demo_fallback"]],
  ["status", ["status_state"]],
  ["status column", ["status_state", "table_structure"]],
  ["stock or shipping summary", ["variant_availability_state", "policy_information"]],
  ["strong hierarchy", ["visual_hierarchy"]],
  ["subtotal", ["pricing_clarity", "cart_management"]],
  ["support link", ["support_contact"]],
  ["support or contact cue", ["support_contact"]],
  ["table or text fallback", ["text_fallback", "accessible_copy"]],
  ["task status", ["task_timeline", "status_state"]],
  ["thread status", ["thread_state", "status_state"]],
  ["timestamp", ["timestamp"]],
  ["transition rules", ["state_taxonomy"]],
  ["trust cue", ["proof_adjacency", "trust_signal"]],
  ["undo or audit log", ["undo_path", "audit_trail"]],
  ["validation states", ["validation_state", "error_state"]],
  ["variant or availability summary", ["variant_availability_state"]],
  ["variant state", ["variant_availability_state"]],
  ["visible CTA", ["dom_text_cta", "cta_path"]],
  ["visible H1", ["visible_h1", "semantic_headings"]],
  ["visible price", ["pricing_clarity"]]
] as const satisfies readonly RequirementAlias[];

const knownRequirementCodes = new Set<string>(PATTERN_REQUIREMENT_CODES);
const requiresAliasByPhrase: ReadonlyMap<string, readonly PatternRequirementCode[]> = new Map(
  REQUIRES_ALIASES.map(([phrase, codes]) => [phrase, codes] as const)
);

export function mapRequiresToCodes(requires: readonly string[]): readonly PatternRequirementCode[] {
  const seen = new Set<PatternRequirementCode>();
  const codes: PatternRequirementCode[] = [];

  for (const requirement of requires) {
    const mappedCodes = requiresAliasByPhrase.get(requirement) ?? [];
    for (const code of mappedCodes) {
      if (!seen.has(code)) {
        seen.add(code);
        codes.push(code);
      }
    }
  }

  return codes;
}

export function isKnownRequirementCode(code: string): boolean {
  return knownRequirementCodes.has(code);
}
