import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { pathToFileURL } from "node:url";

import { writePointCloudDebugOverlay } from "./debug-overlay";
import { assertCanWriteOutputFile, resolveSafeOutputPath } from "./png";
import { imageToPointCloud } from "./sampler";
import type { EncodedPointCloud, ImageToPointCloudOptions } from "./types";

interface CliArgs {
  readonly imagePath: string;
  readonly outPath: string;
  readonly debugPath?: string;
  readonly force: boolean;
  readonly options: ImageToPointCloudOptions;
}

export async function runImagePointCloudCli(argv: readonly string[]): Promise<void> {
  const parsed = parseArgs(argv);
  await assertCanWriteOutputFile(parsed.outPath, parsed.force, "--out");
  if (parsed.debugPath !== undefined) {
    await assertCanWriteOutputFile(parsed.debugPath, parsed.force, "--debug");
  }

  const pointCloud = await imageToPointCloud(parsed.options);

  await mkdir(dirname(parsed.outPath), { recursive: true });
  await writeFile(parsed.outPath, toPointCloudModuleSource(pointCloud));

  if (parsed.debugPath !== undefined) {
    await writePointCloudDebugOverlay({
      imagePath: parsed.imagePath,
      pointCloud,
      outputPath: parsed.debugPath
    });
  }

  console.log(JSON.stringify(pointCloud.stats, null, 2));
}

export function toPointCloudModuleSource(pointCloud: EncodedPointCloud): string {
  return [
    "// Generated by src/lib/image-point-cloud/cli.ts.",
    "// Decode with decodePointCloud from src/lib/image-point-cloud.",
    "",
    `export const pointCloud = ${JSON.stringify(pointCloud, null, 2)} as const;`,
    ""
  ].join("\n");
}

function parseArgs(argv: readonly string[]): CliArgs {
  let imagePath: string | undefined;
  let outPath: string | undefined;
  let debugPath: string | undefined;
  let sampleStep: number | undefined;
  let alphaThreshold: number | undefined;
  let brightnessFloor: number | undefined;
  let depthAmp: number | undefined;
  let seed: string | undefined;
  let targetCount: number | undefined;
  let outputRoot = process.cwd();
  let force = false;

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (arg === "--help" || arg === "-h") {
      throw new Error(getUsage());
    }

    if (arg === "--step") {
      sampleStep = readNumberArg(argv, index, "--step");
      index += 1;
    } else if (arg === "--out") {
      outPath = readStringArg(argv, index, "--out");
      index += 1;
    } else if (arg === "--debug") {
      debugPath = readStringArg(argv, index, "--debug");
      index += 1;
    } else if (arg === "--alpha") {
      alphaThreshold = readNumberArg(argv, index, "--alpha");
      index += 1;
    } else if (arg === "--brightness") {
      brightnessFloor = readNumberArg(argv, index, "--brightness");
      index += 1;
    } else if (arg === "--depth") {
      depthAmp = readNumberArg(argv, index, "--depth");
      index += 1;
    } else if (arg === "--seed") {
      seed = readStringArg(argv, index, "--seed");
      index += 1;
    } else if (arg === "--target-count") {
      targetCount = readNumberArg(argv, index, "--target-count");
      index += 1;
    } else if (arg === "--output-root") {
      outputRoot = readStringArg(argv, index, "--output-root");
      index += 1;
    } else if (arg === "--force") {
      force = true;
    } else if (arg?.startsWith("--") === true) {
      throw new Error(`unknown option: ${arg}\n${getUsage()}`);
    } else if (imagePath === undefined && arg !== undefined) {
      imagePath = arg;
    } else {
      throw new Error(`unexpected argument: ${arg ?? ""}\n${getUsage()}`);
    }
  }

  if (imagePath === undefined || outPath === undefined) {
    throw new Error(getUsage());
  }

  const options: ImageToPointCloudOptions = {
    imagePath,
    ...(sampleStep !== undefined ? { sampleStep } : {}),
    ...(alphaThreshold !== undefined ? { alphaThreshold } : {}),
    ...(brightnessFloor !== undefined ? { brightnessFloor } : {}),
    ...(depthAmp !== undefined ? { depthAmp } : {}),
    ...(seed !== undefined ? { seed } : {}),
    ...(targetCount !== undefined ? { targetCount } : {})
  };

  const resolvedOutPath = resolveSafeOutputPath({
    outputRoot,
    requestedPath: outPath,
    expectedExtension: ".ts",
    label: "--out"
  });
  const resolvedDebugPath = debugPath === undefined
    ? undefined
    : resolveSafeOutputPath({
      outputRoot,
      requestedPath: debugPath,
      expectedExtension: ".png",
      label: "--debug"
    });

  return {
    imagePath,
    outPath: resolvedOutPath,
    ...(resolvedDebugPath !== undefined ? { debugPath: resolvedDebugPath } : {}),
    force,
    options
  };
}

function readStringArg(argv: readonly string[], index: number, name: string): string {
  const value = argv[index + 1];
  if (value === undefined || value.startsWith("--")) {
    throw new Error(`${name} requires a value`);
  }

  return value;
}

function readNumberArg(argv: readonly string[], index: number, name: string): number {
  const value = Number(readStringArg(argv, index, name));
  if (!Number.isFinite(value)) {
    throw new Error(`${name} must be a finite number`);
  }

  return value;
}

function getUsage(): string {
  return [
    "Usage: tsx src/lib/image-point-cloud/cli.ts <imagePath> --out <module.ts> [--step <n>] [--debug <overlay.png>]",
    "Output paths are resolved inside --output-root <dir> (default: cwd); use --force to overwrite existing files.",
    "Optional: --alpha <0..255> --brightness <0..1> --depth <n> --seed <value>",
    "Optional: --target-count <n> (opt-in thinning; can distort or remove source detail)"
  ].join("\n");
}

const entryPath = process.argv[1];
if (entryPath !== undefined && import.meta.url === pathToFileURL(entryPath).href) {
  runImagePointCloudCli(process.argv.slice(2)).catch((error: unknown) => {
    const message = error instanceof Error ? error.message : String(error);
    console.error(message);
    process.exitCode = 1;
  });
}
