import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { describe, expect, it } from "vitest";
import axe from "axe-core";
import type { ApprovalRecord } from "../../types/controlPlane";
import { approvalRiskLabel, boundedPromptPreview, sortApprovals } from "./approvalSelectors";
import { ApprovalPane } from "./ApprovalPane";

const base: ApprovalRecord = { schema_version: "v1", approval_id: "a-1", session_id: "s-1", vendor: "claude_cli", model: "claude", skill_ids: ["model-usage"], prompt_preview: "show usage", prompt_file: null, input_token_bound: 10, output_token_allowance: 15, estimated_tokens: 25, status: "pending", created_at: "2026-07-11T10:00:00.000Z", decided_at: null, rejection_reason: null };
function mount(node: React.ReactNode) { const host = document.createElement("div"); document.body.append(host); const root = createRoot(host); act(() => root.render(node)); return { host, root }; }

describe("approval selectors", () => {
  it("sorts pending first then newest decisions", () => { const result = sortApprovals([{ ...base, approval_id: "old", status: "approved", created_at: "2026-07-11T10:00:00.000Z", decided_at: "2026-07-11T08:00:00.000Z" }, { ...base, approval_id: "new", status: "approved", created_at: "2026-07-11T09:00:00.000Z", decided_at: "2026-07-11T11:00:00.000Z" }, { ...base, approval_id: "pending", created_at: "2026-07-11T07:00:00.000Z" }]); expect(result.map((item) => item.approval_id)).toEqual(["pending", "new", "old"]); });
  it("bounds prompt preview", () => { expect(boundedPromptPreview("x".repeat(600))).toHaveLength(500); expect(boundedPromptPreview("x".repeat(600)).endsWith("…")).toBe(true); });
  it("localizes every approval risk", () => { expect(["low", "medium", "high"].map((risk) => approvalRiskLabel(risk as "low" | "medium" | "high"))).toEqual(["nízké", "střední", "vysoké"]); });
});

describe("ApprovalPane", () => {
  it("renders localized queue metadata and requires confirmation before approval", () => { const medium = { ...base, skill_ids: ["model-usage", "repo-review"], estimated_tokens: 5_000 }; const { host, root } = mount(<ApprovalPane approvals={[medium]} />); expect(host.textContent).toContain("1 schválení"); expect(host.textContent).toContain("1 čeká"); expect(host.textContent).toContain("Čeká"); expect(host.textContent).toContain("Riziko: střední"); expect([...host.querySelectorAll("dt")].map((item) => item.textContent)).toEqual(["Relace", "Skills", "Odhad tokenů", "Povinné kontroly", "Podmínky zastavení"]); expect([...host.querySelectorAll('[role="tab"]')].map((item) => item.textContent)).toEqual(["Prompt", "Diff", "Files", "Plan", "Logs"]); const approve = [...host.querySelectorAll("button")].find((button) => button.textContent === "Schválit") as HTMLButtonElement; act(() => approve.click()); expect(host.textContent).toContain("Schválit tento prompt ke spuštění?"); const confirm = [...host.querySelectorAll("button")].find((button) => button.textContent === "Potvrdit schválení") as HTMLButtonElement; expect(confirm).not.toBeUndefined(); act(() => confirm.click()); act(() => root.unmount()); host.remove(); });
  it("uses Czech pending-count grammar and localized approval states", () => { const approvals: ApprovalRecord[] = [base, { ...base, approval_id: "a-2" }, { ...base, approval_id: "a-3", status: "approved", decided_at: "2026-07-11T11:00:00.000Z" }, { ...base, approval_id: "a-4", status: "rejected", decided_at: "2026-07-11T11:01:00.000Z" }]; const { host, root } = mount(<ApprovalPane approvals={approvals} />); expect(host.textContent).toContain("4 schválení"); expect(host.textContent).toContain("2 čekají"); expect([...host.querySelectorAll(".approval-row-status")].map((item) => item.textContent)).toEqual(["Čeká", "Čeká", "Schváleno", "Zamítnuto"]); act(() => root.unmount()); host.remove(); });
  it("requires a rejection reason and calls callback", () => { const calls: string[] = []; const { host, root } = mount(<ApprovalPane approvals={[base]} onReject={(_, reason) => calls.push(reason)} />); const reject = [...host.querySelectorAll("button")].find((button) => button.textContent === "Zamítnout") as HTMLButtonElement; act(() => reject.click()); const confirm = [...host.querySelectorAll("button")].find((button) => button.textContent === "Potvrdit zamítnutí") as HTMLButtonElement; expect(confirm.disabled).toBe(true); const textarea = host.querySelector("textarea") as HTMLTextAreaElement; act(() => { const setter = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, "value")?.set; setter?.call(textarea, "too risky"); textarea.dispatchEvent(new Event("change", { bubbles: true })); }); const enabledConfirm = [...host.querySelectorAll("button")].find((button) => button.textContent === "Potvrdit zamítnutí") as HTMLButtonElement; act(() => enabledConfirm.click()); expect(calls).toEqual(["too risky"]); act(() => root.unmount()); host.remove(); });
  it("renders detail tabs and API errors", () => { const { host, root } = mount(<ApprovalPane approvals={[base]} error="401 unauthorized" />); expect(host.textContent).toContain("401 unauthorized"); const tabs = [...host.querySelectorAll('[role="tab"]')]; act(() => (tabs[2] as HTMLButtonElement).click()); expect(host.textContent).toContain("Data pro záložku Files nejsou ve snímku schválení dostupná."); act(() => root.unmount()); host.remove(); });
  it("renders conflict errors and disables stale mutations", () => { const { host, root } = mount(<ApprovalPane approvals={[{ ...base, status: "approved", decided_at: "2026-07-11T11:00:00.000Z" }]} error="409 approval already decided" />); expect(host.textContent).toContain("409 approval already decided"); expect([...host.querySelectorAll("button")].find((button) => button.textContent === "Schválit")?.disabled).toBe(true); act(() => root.unmount()); host.remove(); });
  it("has no axe violations", async () => { const { host, root } = mount(<ApprovalPane approvals={[base]} />); const result = await axe.run(host, { rules: { "color-contrast": { enabled: false } } }); expect(result.violations).toEqual([]); act(() => root.unmount()); host.remove(); });
});
