import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { describe, expect, it } from "vitest";
import axe from "axe-core";
import type { ProviderHealth, ProviderModels, ProviderQuota } from "../../types/controlPlane";
import { formatQuotaWindow } from "./quotaSelectors";
import { ProviderPane } from "./ProviderPane";

const quota: ProviderQuota = { provider: "openrouter_api", source: "probe", fetched_at: "2026-07-11T10:00:00.000Z", observed_at: "2026-07-11T10:00:00.000Z", five_hour: { limit: 1000, used: 0, remaining: 1000, resets_at: "2026-07-11T15:00:00.000Z" }, weekly: { limit: null, used: 12, remaining: null, resets_at: null }, api_spend: 1.25, currency: "USD", models: [{ model_id: "nvidia/nemotron", available: true, health: "healthy", source: "Nvidia" }], health: "healthy", error_code: "secret-error", freshness: "fresh", next_poll_at: "2026-07-11T10:05:00.000Z" };
const staleQuota = { ...quota, freshness: "stale" as const, api_spend: null, models: [] };
const health: ProviderHealth = { providers: [{ provider: "openrouter_api", health: "healthy", freshness: "fresh", fetched_at: quota.fetched_at, next_poll_at: quota.next_poll_at, error_code: "raw-provider-error" }] };
const models: ProviderModels = { freshness: "fresh", fetched_at: quota.fetched_at, next_poll_at: quota.next_poll_at, models: [{ model_id: "fallback-model", providers: ["openrouter_api"], available: true, health: ["healthy"], updated_at: "2026-07-11T10:01:00.000Z" }] };
function mount(node: React.ReactNode) { const host = document.createElement("div"); document.body.append(host); const root = createRoot(host); act(() => root.render(node)); return { host, root }; }

describe("ProviderPane", () => {
  it("renders fresh windows, zero usage, spend and models", () => { const { host, root } = mount(<ProviderPane quotas={[quota]} />); expect(host.textContent).toContain("Fresh"); expect(host.textContent).toContain("0 / 1,000 (0%)"); expect(host.textContent).toContain("1.25 USD"); expect(host.textContent).toContain("nvidia/nemotron"); act(() => root.unmount()); host.remove(); });
  it("renders stale warning and never exposes raw provider errors", () => { const { host, root } = mount(<ProviderPane quotas={[staleQuota]} health={health} />); expect(host.textContent).toContain("Stale"); expect(host.textContent).toContain("Provider data is stale"); expect(host.textContent).not.toContain("secret-error"); expect(host.textContent).not.toContain("raw-provider-error"); act(() => root.unmount()); host.remove(); });
  it("does not hide stale model/health data behind a fresh quota", () => { const { host, root } = mount(<ProviderPane quotas={[quota]} models={{ ...models, freshness: "stale" }} health={{ ...health, providers: [{ ...health.providers[0], freshness: "stale" }] }} />); expect(host.textContent).toContain("Some provider data is stale"); expect(host.querySelector(".provider-freshness-stale")).not.toBeNull(); act(() => root.unmount()); host.remove(); });
  it("renders unavailable/null values and model API data", () => { const { host, root } = mount(<ProviderPane quotas={[]} models={models} health={health} />); expect(host.textContent).toContain("Unavailable"); expect(host.textContent).toContain("fallback-model"); act(() => root.unmount()); host.remove(); });
  it("renders provider, availability, health and model update metadata", () => { const { host, root } = mount(<ProviderPane quotas={[]} models={models} health={health} />); expect(host.textContent).toContain("openrouter_api"); expect(host.textContent).toContain("Available"); expect(host.textContent).toContain("healthy"); expect(host.textContent).toContain("2026-07-11T10:01:00.000Z"); expect(host.textContent).toContain("Fetched"); expect(host.textContent).toContain("Next poll"); act(() => root.unmount()); host.remove(); });
  it("renders unavailable provider health without leaking error details", () => { const { host, root } = mount(<ProviderPane quotas={[]} health={{ providers: [{ provider: "codex_cli", health: "unavailable", freshness: "unavailable", fetched_at: "", next_poll_at: null, error_code: "credential-failure" }] }} />); expect(host.textContent).toContain("unavailable"); expect(host.textContent).not.toContain("credential-failure"); act(() => root.unmount()); host.remove(); });
  it("supports provider tabs", () => { const calls: string[] = []; const { host, root } = mount(<ProviderPane quotas={[quota, { ...quota, provider: "claude_cli" }]} onSelectProvider={(provider) => calls.push(provider)} selectedProvider="openrouter_api" />); const button = [...host.querySelectorAll("button")].find((item) => item.textContent === "claude_cli") as HTMLButtonElement; act(() => button.click()); expect(calls).toEqual(["claude_cli"]); act(() => root.unmount()); host.remove(); });
  it("has no axe violations", async () => { const { host, root } = mount(<ProviderPane quotas={[quota]} />); const result = await axe.run(host, { rules: { "color-contrast": { enabled: false } } }); expect(result.violations).toEqual([]); act(() => root.unmount()); host.remove(); });
  it("formats null windows as unavailable", () => { expect(formatQuotaWindow({ limit: null, used: 1, remaining: null, resets_at: null })).toBe("Unavailable"); });
});
